### ISSUE TITLE
discuss about isBlock, isActive of /api/v1/accounts

### ISSUE THREAD

**Issue by VoNhu2901** [VoNhu2901/exchange-document-be#41]
![image](https://user-images.githubusercontent.com/75055290/228713144-8dcee7bd-3ff5-4c9a-a0b5-3953979698d6.png)
![image](https://user-images.githubusercontent.com/75055290/228713342-23aaac5d-3213-41b3-b57a-f24503c7b18b.png)

**Comment by mthuandkp** [comment]
Giải thích rõ hơn xíu đi bà

**Comment by mthuandkp** [comment]
Done
